=== devilmetal/ioox/init/Persons.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="Persons">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" minOccurs="0" name="Person">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="PersonId" type="IdType">
                                <xs:annotation>
                                    <xs:documentation>Internal ID. Indipendent from extern</xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="Lastname" type="xs:string"/>
                            <xs:element name="Firstname" type="xs:string"/>
                            <xs:element name="Username" type="xs:string">
                                <xs:annotation>
                                    <xs:documentation>username is the same of the DB exist</xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="UniqueID" type="xs:string">
                                <xs:annotation>
                                    <xs:documentation>ref to uiqueID university system</xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="Engagments">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element maxOccurs="unbounded" minOccurs="0"
                                            name="Engagment">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element name="EngagementId"/>
                                                  <xs:element name="Role"/>
                                                  <xs:element name="CoursRef"/>
                                                  <xs:element maxOccurs="1" minOccurs="0"
                                                  name="Grade">
                                                  <xs:complexType>
                                                  <xs:sequence>
                                                  <xs:element minOccurs="0" name="ProjectGrades">
                                                  <xs:complexType>
                                                  <xs:sequence>
                                                  <xs:element maxOccurs="unbounded" name="Step">
                                                  <xs:complexType>
                                                  <xs:sequence>
                                                  <xs:element name="StepNo"
                                                  type="xs:nonNegativeInteger"/>
                                                  <xs:element name="StepGrade" type="GradeType"/>
                                                  </xs:sequence>
                                                  </xs:complexType>
                                                  </xs:element>
                                                  </xs:sequence>
                                                  </xs:complexType>
                                                  </xs:element>
                                                  <xs:element minOccurs="0" name="ExamGrade"
                                                  type="GradeType"/>
                                                  <xs:element minOccurs="0" name="ExercicesGrades">
                                                  <xs:complexType>
                                                  <xs:sequence maxOccurs="1" minOccurs="1">
                                                  <xs:element maxOccurs="unbounded" name="Exercice"
                                                  minOccurs="0">
                                                  <xs:complexType>
                                                  <xs:sequence>
                                                  <xs:element name="ExerciceId"
                                                  type="xs:nonNegativeInteger"/>
                                                  <xs:element name="ExerciceGrade" type="GradeType"
                                                  />
                                                  </xs:sequence>
                                                  </xs:complexType>
                                                  </xs:element>
                                                  </xs:sequence>
                                                  </xs:complexType>
                                                  </xs:element>
                                                  </xs:sequence>
                                                  </xs:complexType>
                                                  </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="ToDoList">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element maxOccurs="unbounded" minOccurs="0"
                                            name="Activity">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element name="Title" type="xs:string"/>
                                                  <xs:element name="Tasks">
                                                  <xs:complexType>
                                                  <xs:sequence>
                                                  <xs:element maxOccurs="unbounded" minOccurs="0"
                                                  name="Task">
                                                  <xs:complexType>
                                                  <xs:sequence>
                                                  <xs:element name="Title" type="xs:string"/>
                                                  <xs:element name="Description" type="ContentType"/>
                                                  <xs:element name="Priority" type="PriorityType"/>
                                                  <xs:element minOccurs="0" name="Deadline"
                                                  type="DeadlineType"/>
                                                  </xs:sequence>
                                                  </xs:complexType>
                                                  </xs:element>
                                                  </xs:sequence>
                                                  </xs:complexType>
                                                  </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Notes">
                                <xs:complexType>
                                    <xs:sequence maxOccurs="unbounded" minOccurs="0">
                                        <xs:element name="Note">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element name="NoteId"/>
                                                  <xs:element name="CourseRef"/>
                                                  <xs:element name="SessionRef"/>
                                                  <xs:element name="Content" type="ContentType"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Token" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="IdType">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="-1"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="WeightType">
        <xs:annotation>
            <xs:documentation>Percentage: nb between 1 and 100</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:positiveInteger">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="100"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="GradeType">
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="6"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="ContentType">
        <xs:choice maxOccurs="unbounded" minOccurs="0">
            <xs:element name="Parag" type="ParagType"/>
            <xs:element name="List" type="ListType"/>
        </xs:choice>
    </xs:complexType>
    <xs:simpleType name="PriorityType">
        <xs:annotation>
            <xs:documentation>To specify a priority for the to do list actions</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:positiveInteger">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="3"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="DeadlineType">
        <xs:sequence>
            <xs:element name="Date" type="xs:date"/>
            <xs:element minOccurs="0" name="Time" type="xs:time"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="ParagType">
        <xs:choice maxOccurs="unbounded">
            <xs:element name="Fragment" type="FragmentType"/>
            <xs:element name="Link" type="LinkType"/>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="ListType">
        <xs:sequence>
            <xs:element minOccurs="0" name="ListHeader" type="xs:string"/>
            <xs:choice>
                <xs:element maxOccurs="unbounded" name="ListItem">
                    <xs:complexType>
                        <xs:choice maxOccurs="unbounded">
                            <xs:element name="Fragment" type="FragmentType"/>
                            <xs:element name="Link" type="LinkType"/>
                        </xs:choice>
                    </xs:complexType>
                </xs:element>
                <xs:element maxOccurs="unbounded" name="SubList">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element minOccurs="0" name="SubListHeader" type="xs:string"/>
                            <xs:element maxOccurs="unbounded" name="SubListItem">
                                <xs:complexType>
                                    <xs:choice maxOccurs="unbounded">
                                        <xs:element name="Fragment" type="FragmentType"/>
                                        <xs:element name="Link" type="LinkType"/>
                                    </xs:choice>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:choice>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="LinkType">
        <xs:sequence>
            <xs:element name="LinkText" type="xs:string"/>
            <xs:element name="LinkRef" type="xs:anyURI"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="DocumentRefType">
        <xs:sequence>
            <xs:element name="Title" type="xs:string"/>
            <xs:element maxOccurs="unbounded" minOccurs="1" name="Access">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Location" type="xs:anyURI"/>
                        <xs:element name="Format" type="FileFormatType"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="FragmentType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="FragmentKind" type="xs:string" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:simpleType name="FileFormatType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Undefined"/>
            <xs:enumeration value="DOC"/>
            <xs:enumeration value="HTML"/>
            <xs:enumeration value="PDF"/>
            <xs:enumeration value="RTF"/>
            <xs:enumeration value="XLS"/>
            <xs:enumeration value="XML"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== devilmetal/ioox/init/Persons.xml
<?xml version="1.0" encoding="UTF-8"?>
<Persons xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:./Persons.xsd">
    <Person>
        <PersonId>50</PersonId>
        <Lastname>Luyet</Lastname>
        <Firstname>Gil</Firstname>
        <Username>luyetg</Username>
        <Password>123</Password>
        <Engagments>
            <Engagment>
                <EngagementId>1</EngagementId>
                <Role>Student</Role>
                <CoursRef>4112</CoursRef>
                <Grade>
                    <ProjectGrades>
                        <Step>
                            <StepNo>75</StepNo>
                            <StepGrade>5</StepGrade>
                        </Step>
                        <Step>
                            <StepNo>25</StepNo>
                            <StepGrade>4</StepGrade>
                        </Step>
                    </ProjectGrades>
                    <ExamGrade>6</ExamGrade>
                </Grade>
            </Engagment>
            <Engagment>
                <EngagementId>2</EngagementId>
                <Role>Tutor</Role>
                <CoursRef>4112</CoursRef>
            </Engagment>
        </Engagments>
        <ToDoList/>
    </Person>
    <Person>
        <PersonId>51</PersonId>
        <Lastname>Carnevale</Lastname>
        <Firstname>Luca</Firstname>
        <Username>carnevlu</Username>
        <Password>123</Password>
        <Engagments>
            <Engagment>
                <EngagementId>3</EngagementId>
                <Role>Tutor</Role>
                <CoursRef>4112</CoursRef>
            </Engagment>
        </Engagments>
        <ToDoList>
            <Activity>
                <Title>Title6</Title>
                <Tasks>
                    <Task>
                        <Title>Title7</Title>
                        <Description>
                            <List>
                                <SubList>
                                    <SubListItem>
                                        <Link>
                                            <LinkText>LinkText12</LinkText>
                                            <LinkRef>http://www.oxygenxml.com/</LinkRef>
                                        </Link>
                                        <Fragment>Fragment14</Fragment>
                                    </SubListItem>
                                    <SubListItem>
                                        <Link>
                                            <LinkText>LinkText13</LinkText>
                                            <LinkRef>http://www.oxygenxml.com/</LinkRef>
                                        </Link>
                                        <Link>
                                            <LinkText>LinkText14</LinkText>
                                            <LinkRef>http://www.oxygenxml.com/</LinkRef>
                                        </Link>
                                    </SubListItem>
                                </SubList>
                                <SubList>
                                    <SubListItem>
                                        <Link>
                                            <LinkText>LinkText15</LinkText>
                                            <LinkRef>http://www.oxygenxml.com/</LinkRef>
                                        </Link>
                                        <Link>
                                            <LinkText>LinkText16</LinkText>
                                            <LinkRef>http://www.oxygenxml.com/</LinkRef>
                                        </Link>
                                    </SubListItem>
                                    <SubListItem>
                                        <Fragment>Fragment15</Fragment>
                                        <Link>
                                            <LinkText>LinkText17</LinkText>
                                            <LinkRef>http://www.oxygenxml.com/</LinkRef>
                                        </Link>
                                    </SubListItem>
                                </SubList>
                            </List>
                            <List>
                                <SubList>
                                    <SubListItem>
                                        <Fragment>Fragment16</Fragment>
                                        <Fragment>Fragment17</Fragment>
                                    </SubListItem>
                                    <SubListItem>
                                        <Link>
                                            <LinkText>LinkText18</LinkText>
                                            <LinkRef>http://www.oxygenxml.com/</LinkRef>
                                        </Link>
                                        <Link>
                                            <LinkText>LinkText19</LinkText>
                                            <LinkRef>http://www.oxygenxml.com/</LinkRef>
                                        </Link>
                                    </SubListItem>
                                </SubList>
                                <SubList>
                                    <SubListItem>
                                        <Fragment>Fragment18</Fragment>
                                        <Link>
                                            <LinkText>LinkText20</LinkText>
                                            <LinkRef>http://www.oxygenxml.com/</LinkRef>
                                        </Link>
                                    </SubListItem>
                                    <SubListItem>
                                        <Link>
                                            <LinkText>LinkText21</LinkText>
                                            <LinkRef>http://www.oxygenxml.com/</LinkRef>
                                        </Link>
                                        <Fragment>Fragment19</Fragment>
                                    </SubListItem>
                                </SubList>
                            </List>
                        </Description>
                        <Priority>2</Priority>
                    </Task>
                    <Task>
                        <Title>Title8</Title>
                        <Description>
                            <List>
                                <ListItem>
                                    <Link>
                                        <LinkText>LinkText22</LinkText>
                                        <LinkRef>http://www.oxygenxml.com/</LinkRef>
                                    </Link>
                                    <Fragment>Fragment20</Fragment>
                                </ListItem>
                                <ListItem>
                                    <Fragment>Fragment21</Fragment>
                                    <Fragment>Fragment22</Fragment>
                                </ListItem>
                            </List>
                            <List>
                                <ListItem>
                                    <Fragment>Fragment23</Fragment>
                                    <Link>
                                        <LinkText>LinkText23</LinkText>
                                        <LinkRef>http://www.oxygenxml.com/</LinkRef>
                                    </Link>
                                </ListItem>
                                <ListItem>
                                    <Link>
                                        <LinkText>LinkText24</LinkText>
                                        <LinkRef>http://www.oxygenxml.com/</LinkRef>
                                    </Link>
                                    <Link>
                                        <LinkText>LinkText25</LinkText>
                                        <LinkRef>http://www.oxygenxml.com/</LinkRef>
                                    </Link>
                                </ListItem>
                            </List>
                        </Description>
                        <Priority>2</Priority>
                    </Task>
                </Tasks>
            </Activity>
            <Activity>
                <Title>Title9</Title>
                <Tasks>
                    <Task>
                        <Title>Title10</Title>
                        <Description>
                            <Parag>
                                <Link>
                                    <LinkText>LinkText26</LinkText>
                                    <LinkRef>http://www.oxygenxml.com/</LinkRef>
                                </Link>
                                <Fragment>Fragment24</Fragment>
                            </Parag>
                            <Parag>
                                <Link>
                                    <LinkText>LinkText27</LinkText>
                                    <LinkRef>http://www.oxygenxml.com/</LinkRef>
                                </Link>
                                <Fragment>Fragment25</Fragment>
                            </Parag>
                        </Description>
                        <Priority>2</Priority>
                    </Task>
                    <Task>
                        <Title>Title11</Title>
                        <Description>
                            <List>
                                <ListItem>
                                    <Fragment>Fragment26</Fragment>
                                    <Fragment>Fragment27</Fragment>
                                </ListItem>
                                <ListItem>
                                    <Fragment>Fragment28</Fragment>
                                    <Link>
                                        <LinkText>LinkText28</LinkText>
